<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        Plan::query()->updateOrCreate(
            ['slug' => 'free'],
            [
                'name' => 'Free',
                'description' => 'Get started with basic automation',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'limits' => [
                    'credits_monthly' => 1000,
                    'active_workflows' => 3,
                    'members' => 1,
                    'min_schedule_interval' => 15,
                    'max_execution_time' => 300,
                    'max_file_size_mb' => 5,
                    'data_transfer_gb' => 0.5,
                    'concurrent_executions' => 1,
                    'api_rate_limit_per_min' => 0,
                    'execution_log_days' => 3,
                    'max_saved_executions' => 500,
                    'webhooks' => 1,
                    'credentials' => 5,
                    'variables' => 10,
                    'workflow_versions' => 3,
                    'ai_generation_daily' => 5,
                ],
                'features' => [
                    'webhooks' => false,
                    'api_access' => false,
                    'custom_variables' => false,
                    'sub_workflows' => false,
                    'parallel_execution' => false,
                    'priority_execution' => false,
                    'full_text_log_search' => false,
                    'deterministic_replay' => false,
                    'import_export' => false,
                    'ai_autofix' => false,
                    'ai_generation' => false,
                    'approval_workflows' => false,
                    'workspace_policies' => false,
                    'environments' => false,
                    'analytics_dashboard' => false,
                    'connector_metrics' => false,
                    'execution_runbooks' => false,
                    'audit_logs' => false,
                    'sso_saml' => false,
                    'custom_node_types' => false,
                    'overage_protection' => false,
                    'priority_support' => false,
                ],
                'credit_tiers' => null,
                'is_active' => true,
                'sort_order' => 0,
            ]
        );

        Plan::query()->updateOrCreate(
            ['slug' => 'starter'],
            [
                'name' => 'Starter',
                'description' => 'For solo builders getting productive with automation',
                'price_monthly' => 900,
                'price_yearly' => 8400,
                'limits' => [
                    'credits_monthly' => 10000,
                    'active_workflows' => 20,
                    'members' => 3,
                    'min_schedule_interval' => 5,
                    'max_execution_time' => 900,
                    'max_file_size_mb' => 50,
                    'data_transfer_gb' => 5,
                    'concurrent_executions' => 5,
                    'api_rate_limit_per_min' => 30,
                    'execution_log_days' => 14,
                    'max_saved_executions' => 5000,
                    'webhooks' => 10,
                    'credentials' => 20,
                    'variables' => 50,
                    'workflow_versions' => 10,
                    'ai_generation_daily' => 50,
                ],
                'features' => [
                    'webhooks' => true,
                    'api_access' => true,
                    'custom_variables' => false,
                    'sub_workflows' => false,
                    'parallel_execution' => false,
                    'priority_execution' => false,
                    'full_text_log_search' => false,
                    'deterministic_replay' => false,
                    'import_export' => true,
                    'ai_autofix' => false,
                    'ai_generation' => 'basic',
                    'approval_workflows' => false,
                    'workspace_policies' => false,
                    'environments' => false,
                    'analytics_dashboard' => false,
                    'connector_metrics' => false,
                    'execution_runbooks' => false,
                    'audit_logs' => false,
                    'sso_saml' => false,
                    'custom_node_types' => false,
                    'overage_protection' => false,
                    'priority_support' => false,
                ],
                'credit_tiers' => [10000, 20000, 40000],
                'is_active' => true,
                'sort_order' => 1,
            ]
        );

        Plan::query()->updateOrCreate(
            ['slug' => 'pro'],
            [
                'name' => 'Pro',
                'description' => 'For power users with advanced automation needs',
                'price_monthly' => 2900,
                'price_yearly' => 28800,
                'limits' => [
                    'credits_monthly' => 50000,
                    'active_workflows' => -1,
                    'members' => 10,
                    'min_schedule_interval' => 1,
                    'max_execution_time' => 2400,
                    'max_file_size_mb' => 150,
                    'data_transfer_gb' => 25,
                    'concurrent_executions' => 20,
                    'api_rate_limit_per_min' => 60,
                    'execution_log_days' => 30,
                    'max_saved_executions' => 25000,
                    'webhooks' => 50,
                    'credentials' => 100,
                    'variables' => 200,
                    'workflow_versions' => 50,
                    'ai_generation_daily' => 200,
                ],
                'features' => [
                    'webhooks' => true,
                    'api_access' => true,
                    'custom_variables' => true,
                    'sub_workflows' => true,
                    'parallel_execution' => true,
                    'priority_execution' => 'high',
                    'full_text_log_search' => true,
                    'deterministic_replay' => true,
                    'import_export' => true,
                    'ai_autofix' => true,
                    'ai_generation' => true,
                    'approval_workflows' => false,
                    'workspace_policies' => false,
                    'environments' => false,
                    'analytics_dashboard' => 'basic',
                    'connector_metrics' => false,
                    'execution_runbooks' => false,
                    'audit_logs' => false,
                    'sso_saml' => false,
                    'custom_node_types' => false,
                    'overage_protection' => false,
                    'priority_support' => false,
                ],
                'credit_tiers' => [10000, 20000, 40000, 80000, 150000],
                'is_active' => true,
                'sort_order' => 2,
            ]
        );

        Plan::query()->updateOrCreate(
            ['slug' => 'teams'],
            [
                'name' => 'Teams',
                'description' => 'For teams automating across multiple workflows at scale',
                'price_monthly' => 9900,
                'price_yearly' => 94800,
                'limits' => [
                    'credits_monthly' => 200000,
                    'active_workflows' => -1,
                    'members' => 50,
                    'min_schedule_interval' => 1,
                    'max_execution_time' => 2400,
                    'max_file_size_mb' => 500,
                    'data_transfer_gb' => 100,
                    'concurrent_executions' => 50,
                    'api_rate_limit_per_min' => 240,
                    'execution_log_days' => 90,
                    'max_saved_executions' => 100000,
                    'webhooks' => -1,
                    'credentials' => -1,
                    'variables' => -1,
                    'workflow_versions' => -1,
                    'ai_generation_daily' => 1000,
                ],
                'features' => [
                    'webhooks' => true,
                    'api_access' => true,
                    'custom_variables' => true,
                    'sub_workflows' => true,
                    'parallel_execution' => true,
                    'priority_execution' => 'priority',
                    'full_text_log_search' => true,
                    'deterministic_replay' => true,
                    'import_export' => true,
                    'ai_autofix' => true,
                    'ai_generation' => true,
                    'approval_workflows' => true,
                    'workspace_policies' => true,
                    'environments' => true,
                    'analytics_dashboard' => true,
                    'connector_metrics' => true,
                    'execution_runbooks' => true,
                    'audit_logs' => false,
                    'sso_saml' => false,
                    'custom_node_types' => false,
                    'overage_protection' => true,
                    'priority_support' => true,
                ],
                'credit_tiers' => [10000, 20000, 40000, 80000, 150000, 300000, 500000, 1000000],
                'is_active' => true,
                'sort_order' => 3,
            ]
        );

        Plan::query()->updateOrCreate(
            ['slug' => 'enterprise'],
            [
                'name' => 'Enterprise',
                'description' => 'For organizations with advanced security, compliance, and scale requirements',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'limits' => [
                    'credits_monthly' => -1,
                    'active_workflows' => -1,
                    'members' => -1,
                    'min_schedule_interval' => 1,
                    'max_execution_time' => 3600,
                    'max_file_size_mb' => 1024,
                    'data_transfer_gb' => -1,
                    'concurrent_executions' => 200,
                    'api_rate_limit_per_min' => 1000,
                    'execution_log_days' => 365,
                    'max_saved_executions' => -1,
                    'webhooks' => -1,
                    'credentials' => -1,
                    'variables' => -1,
                    'workflow_versions' => -1,
                    'ai_generation_daily' => -1,
                ],
                'features' => [
                    'webhooks' => true,
                    'api_access' => true,
                    'custom_variables' => true,
                    'sub_workflows' => true,
                    'parallel_execution' => true,
                    'priority_execution' => 'priority',
                    'full_text_log_search' => true,
                    'deterministic_replay' => true,
                    'import_export' => true,
                    'ai_autofix' => true,
                    'ai_generation' => true,
                    'approval_workflows' => true,
                    'workspace_policies' => true,
                    'environments' => true,
                    'analytics_dashboard' => true,
                    'connector_metrics' => true,
                    'execution_runbooks' => true,
                    'audit_logs' => true,
                    'sso_saml' => true,
                    'custom_node_types' => true,
                    'overage_protection' => true,
                    'priority_support' => true,
                ],
                'credit_tiers' => null,
                'is_active' => true,
                'sort_order' => 4,
            ]
        );
    }
}
